"""
State Crime Census 2022 — Groq API Analyzer
Reads state_crime_census_2022.csv, sends each state's data to a Groq-hosted
LLM, and writes a Markdown summary report to state_crime_analysis_report.md

Setup:
  1. Sign up for a free API key at https://console.groq.com
  2. pip install groq
  3. export GROQ_API_KEY='gsk_...'
  4. python analyze_crime_data.py
"""

import csv
import json
import os
from groq import Groq

# ── Configuration ──────────────────────────────────────────────────────────────
CSV_PATH    = "state_crime_census_2022.csv"   # put the CSV next to this script
OUTPUT_PATH = "state_crime_analysis_report.md"
MODEL       = "llama-3.3-70b-versatile"       # fast & free on Groq's free tier
MAX_TOKENS  = 1024

# ── Helpers ────────────────────────────────────────────────────────────────────

def load_csv(path: str) -> list[dict]:
    """Return all rows as a list of dicts."""
    with open(path, newline="", encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def build_prompt(row: dict) -> str:
    """Format a single state row into a structured analysis prompt."""
    return f"""You are a crime-data analyst. Analyze the following 2022 statistics for {row['NAME']} and produce a concise summary covering:

1. **Crime Overview** – total incidents, offenses, victims, and crime rate per 100k residents.
2. **Clearance Rate** – how effectively crimes were resolved.
3. **Socioeconomic Context** – median household income, unemployment, poverty rate, and education level, and how they may relate to the crime figures.
4. **Demographic Notes** – racial/ethnic composition and housing vacancy rate in relation to crime patterns.
5. **Key Takeaways** – 2-3 bullet points highlighting the most notable findings.

State data (JSON):
{json.dumps(row, indent=2)}

Keep the summary under 300 words and use clear Markdown formatting."""


def analyze_state(client: Groq, row: dict) -> str:
    """Call the Groq API and return the assistant's text response."""
    response = client.chat.completions.create(
        model=MODEL,
        max_tokens=MAX_TOKENS,
        messages=[{"role": "user", "content": build_prompt(row)}],
    )
    return response.choices[0].message.content


def compute_aggregate_stats(rows: list[dict]) -> dict:
    """Compute simple aggregate statistics across all states."""
    def avg(key):
        vals = [float(r[key]) for r in rows if r.get(key) not in ("", None)]
        return sum(vals) / len(vals) if vals else 0

    def extremes(key):
        vals = [(r["NAME"], float(r[key])) for r in rows if r.get(key) not in ("", None)]
        return max(vals, key=lambda x: x[1]), min(vals, key=lambda x: x[1])

    crime_max, crime_min = extremes("crime_rate_per_100k")
    income_max, income_min = extremes("median_household_income")

    return {
        "avg_crime_rate":   round(avg("crime_rate_per_100k"), 2),
        "avg_income":       round(avg("median_household_income"), 2),
        "avg_unemployment": round(avg("unemployment_rate_pct"), 2),
        "avg_poverty":      round(avg("poverty_rate_pct"), 2),
        "highest_crime":    crime_max,
        "lowest_crime":     crime_min,
        "highest_income":   income_max,
        "lowest_income":    income_min,
    }


# ── Main ───────────────────────────────────────────────────────────────────────

def main():
    api_key = os.environ.get("GROQ_API_KEY")

    client = Groq(api_key=api_key)
    rows   = load_csv(CSV_PATH)
    stats  = compute_aggregate_stats(rows)

    print(f"Loaded {len(rows)} states. Starting analysis with Groq ({MODEL})...\n")

    report_lines: list[str] = [
        "# State Crime Census 2022 — Analysis Report",
        "",
        f"> Generated by the Groq API using {MODEL}.",
        "",
        "---",
        "",
        "## National Aggregate Statistics",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Average crime rate (per 100k) | {stats['avg_crime_rate']} |",
        f"| Average median household income | ${stats['avg_income']:,.0f} |",
        f"| Average unemployment rate | {stats['avg_unemployment']}% |",
        f"| Average poverty rate | {stats['avg_poverty']}% |",
        f"| Highest crime rate | {stats['highest_crime'][0]} ({stats['highest_crime'][1]}/100k) |",
        f"| Lowest crime rate  | {stats['lowest_crime'][0]} ({stats['lowest_crime'][1]}/100k) |",
        f"| Highest median income | {stats['highest_income'][0]} (${stats['highest_income'][1]:,.0f}) |",
        f"| Lowest median income  | {stats['lowest_income'][0]} (${stats['lowest_income'][1]:,.0f}) |",
        "",
        "---",
        "",
        "## Per-State Analyses",
        "",
    ]

    for i, row in enumerate(rows, 1):
        state_name = row.get("NAME", f"State {i}")
        print(f"  [{i:02d}/{len(rows)}] Analyzing {state_name}...")

        try:
            analysis = analyze_state(client, row)
        except Exception as exc:
            analysis = f"_Error during analysis: {exc}_"

        report_lines += [
            f"### {state_name}",
            "",
            analysis,
            "",
            "---",
            "",
        ]

    # Write report
    report_text = "\n".join(report_lines)
    with open(OUTPUT_PATH, "w", encoding="utf-8") as fh:
        fh.write(report_text)

    print(f"\n✅  Done! Report saved to: {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
